@startuml
'https://plantuml.com/class-diagram

interface WatermarkGenerator
class BoundedOutOfOrdernessWatermarks
class NoWatermarksGenerator
class AscendingTimestampsWatermarks

WatermarkGenerator <|-- BoundedOutOfOrdernessWatermarks
WatermarkGenerator <|-- NoWatermarksGenerator
WatermarkGenerator <|-- WatermarksWithIdleness
BoundedOutOfOrdernessWatermarks <|-- AscendingTimestampsWatermarks
@enduml