@startuml
'https://plantuml.com/class-diagram

interface State
interface ListState<T>
interface ReadOnlyBroadcastState<K, V>
interface BroadcastState<K, V>


State <|-- ListState
State <|-- ReadOnlyBroadcastState
ReadOnlyBroadcastState <|-- BroadcastState


@enduml